### PR TITLE
Substitute value of dcf_path to an absolute path during build

### PR DESCRIPTION
**Pull request by bjsowa**

### CODE REVIEW

**Comment by ipa-cmh** [comment]
Looks like a good idea. Will test it on my setup and either comeback to you in a few days or merge it directly. Thanks for the contribution!

**Comment by bjsowa** [comment]
Not sure why the workflow is failing. Could you run it again?

**Comment by bjsowa** [comment]
This is only my proposal for not having to work with relative paths. I'm happy to discuss other possibilities.

**Comment by ipa-cmh** [comment]
@bjsowa I is a great feature, it will remove the need to specify the path in the bus.yml file and enforce the standardisation of the configuration folders.

All checks have passed. Can you add a short sentence about this feature in the table here:
https://github.com/ros-industrial/ros2_canopen/blob/master/canopen/sphinx/user-guide/configuration/configuration.rst?

That would be super nice and then this would be ready to merge.

**Review by ipa-cmh — APPROVED** [review]

**Pull request merged**
