### PR TITLE
Robot system interface

### PR DESCRIPTION
**Pull request by ipa-cmh**
This system interface implementation uses the perform switch function to directly switch the CANopen controlled robot into operation enable state and the appropriate operation mode, depending on the command interfaces claimed by controllers.

An appropriate ros2_control xacro yould look like this.
```XML
<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="prbt_ros2_control" params="
      name
      prefix
      bus_config
      master_config
      can_interface_name
      master_bin">

        <ros2_control name="${name}" type="system">
            <hardware>
                <plugin>canopen_ros2_control/RobotSystem</plugin>
                <param name="bus_config">${bus_config}</param>
                <param name="master_config">${master_config}</param>
                <param name="can_interface_name">${can_interface_name}</param>
                <param name="master_bin">"${master_bin}"</param>
            </hardware>
            <joint name="${prefix}joint_1">
                <param name="device_name">prbt_joint_1</param>
            </joint>
            <joint name="${prefix}joint_2">
                <param name="device_name">prbt_joint_2</param>
            </joint>
            <joint name="${prefix}joint_3">
                <param name="device_name">prbt_joint_3</param>
            </joint>
            <joint name="${prefix}joint_4">
                <param name="device_name">prbt_joint_4</param>
            </joint>
            <joint name="${prefix}joint_5">
                <param name="device_name">prbt_joint_5</param>
            </joint>
            <joint name="${prefix}joint_6">
                <param name="device_name">prbt_joint_6</param>
            </joint>
        </ros2_control>

    </xacro:macro>

</robot>
```

The bus configuration file can contain the following:

```YAML
joint_1:
  node_id: 2
  dcf: "cia402_slave.eds"
  driver: "ros2_canopen::Cia402Driver"
  package: "canopen_402_driver"
  period: 10
  position_mode: 1     # Operation mode for position control, only required when used
  velocity_mode: 3     # Operation mode for velocity control, only required when used
  effort_mode: 4         # Operation mode for effort control, only required when used
  switching_state: 2    # 402 state in which the device has to be to switch operation mode.
```

This supersedes #102.
It dependes on #110

### CODE REVIEW

**Comment by ipa-cmh** [comment]
@ipa-vsp can you test this on the PRBT robot? I have made the necessary changes to work with fake slaves see https://github.com/ipa-cmh/prbt_robot/pull/4

To test you can run:
```bash
ros2 launch prbt_robot_support prbt_ros2_control.launch.py
```

**Comment by ipa-vsp** [comment]
Unfortunately, the robot vibration is not entirely eliminated. It is minimal but noticeable. But far better than the old interface.

**Comment by jclinton830** [comment]
@ipa-cmh @ipa-vsp when will you be merging this with the master? Is there more testing that needs to happen?

**Comment by ipa-cmh** [comment]
Yes we will be merging it for the next beta release. I just have to find the time to resolve the conflicts. I hope to do it this  week. There are still one issues to be aware of when using. The problem is, that mode switching in ros2_control is done in the realtime loop. Our experience is, that mode switching in canopen cia402 is not really deterministic and would block the realtime loop. Consequently, we detach the mode switching function into a thread but this means we do not exactly know when switching is finished. So after activation of a controller, we currently do not know when the right operation mode is actually available.

**Pull request merged**
