### PR TITLE
Use 'can_interface_name' consistently everywhere.

### PR DESCRIPTION
**Pull request by destogl**
There is a bit of a mix of `can_interface_name` and `can_interface` usage in some files and documentation.

I propose here that we use consistently everywhere `can_interface_name` to avoid confusion of users.

### CODE REVIEW

**Comment by ipa-cmh** [comment]
Agreed. Wanted to fix that at some point, so greatly appreciated!

**Comment by ipa-cmh** [comment]
We need to sync with #131.

**Comment by destogl** [comment]
Which do you want merge first?

**Comment by destogl** [comment]
Go with #131 then I can rebase

**Pull request merged**
